version: '3.3'

services:
  db:
    image: mariadb:10.5.4
    volumes:
      - ./sample_data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
  bananatv:
    depends_on:
      - db
    image: wordpress:php7.4
    volumes:
      - ./zshl-registration:/var/www/html/wp-content/plugins/zshl-registration
    ports:
      - "8000:80"
    restart: always
    environment:
    - WORDPRESS_DB_HOST=db:3306
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=wordpress
    - WP_DEBUG=true
    - WP_DEBUG_DISPLAY=true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: somewordpress
volumes:
    dbdata:

